insert into Grupo values (1, 'Acidentes Pessoais', '', imgGrupo)
insert into Grupo values (2, 'Aero', '', imgGrupo)
insert into Grupo values (3, 'Ambiental', '', imgGrupo)
insert into Grupo values (4, 'Animal', '', imgGrupo)
insert into Grupo values (5, 'Automóvel', '', imgGrupo)
insert into Grupo values (6, 'Bike', '', imgGrupo)
insert into Grupo values (7, 'Condomínio', '', imgGrupo)
insert into Grupo values (8, 'Consórcio', '', imgGrupo)
insert into Grupo values (9, 'Dental', '', imgGrupo)
insert into Grupo values (10, 'Empresarial', '', imgGrupo)
insert into Grupo values (11, 'Fiança', '', imgGrupo)
insert into Grupo values (12, 'Garantia', '', imgGrupo)
insert into Grupo values (13, 'Náutico', '', imgGrupo)
insert into Grupo values (14, 'Previdência', '', imgGrupo)
insert into Grupo values (15, 'Responsabilidade Civil Profissional', '', imgGrupo)
insert into Grupo values (16, 'Residencial', '', imgGrupo)
insert into Grupo values (17, 'Responsabilidade Civil', '', imgGrupo)
insert into Grupo values (18, 'Risco Engenharia', '', imgGrupo)
insert into Grupo values (19, 'Riscos Diversos', '', imgGrupo)
insert into Grupo values (19, 'Saúde', '', imgGrupo)
insert into Grupo values (19, 'Transporte', '', imgGrupo)
insert into Grupo values (19, 'Vida', '', imgGrupo)

insert into Produto values (cod, nome, codGrupo, descricao, img, email, tags)

insert into Produto values (1, 'Acidentes Pessoais', 1, 'Diversas modalidades - Moto Táxi, Moto Frete, caminhoneiros, passageiros - possibilidade para seguros auxilio funeral, dit', img, 'Raya, Sergio, Edeval', tags)
insert into Produto values (2, 'Aeronáutico', 2, desc, img, emails, tags)
insert into Produto values (3, 'Responsabilidade Civil Ambiental', 3, desc, img, emails, tags)
insert into Produto values (4, 'Animais', 4, desc, img, emails, tags)
insert into Produto values (5, 'Automóvel', 5, desc, img, emails, tags)
insert into Produto values (6, 'Condomínio', 7, desc, img, emails, tags)
insert into Produto values (7, 'Dental Individual E Coletivo', 9, desc, img, emails, tags)
insert into Produto values (8, 'Dpem (Seguro Obrigatório Para Embarcações)', 13, desc, img, emails, tags)
insert into Produto values (9, 'Empresarial', 10, desc, img, emails, tags)
insert into Produto values (10, 'Fiança Capitalização', 11, desc, img, emails, tags)
insert into Produto values (11, 'Fiança Locatícia', 11, desc, img, emails, tags)
insert into Produto values (12, 'Frota', 5, desc, img, emails, tags)
insert into Produto values (13, 'Garantia', 12, desc, img, emails, tags)
insert into Produto values (14, 'Garantia Adiantamento De Pagamento', 12, desc, img, emails, tags)
insert into Produto values (15, 'Garantia Aduaneira', 12, desc, img, emails, tags)
insert into Produto values (16, 'Garantia Do Executante Construtor', 12, desc, img, emails, tags)
insert into Produto values (17, 'Garantia Do Executante Fornecedor', 12, desc, img, emails, tags)
insert into Produto values (18, 'Garantia Do Executante Prestador De Serviços', 12, desc, img, emails, tags)
insert into Produto values (19, 'Garantia Do Licitante (Big Bond)', 12, desc, img, emails, tags)
insert into Produto values (20, 'Garantia Imobiliária', 12, desc, img, emails, tags)
insert into Produto values (21, 'Garantia Manutenção Corretiva', 12, desc, img, emails, tags)
insert into Produto values (22, 'Garantia Para Concessões Públicas', 12, desc, img, emails, tags)
insert into Produto values (23, 'Garantia Para O Setor Energético', 12, desc, img, emails, tags)
insert into Produto values (24, 'Garantia Retenção De Pagamento', 12, desc, img, emails, tags)
insert into Produto values (25, 'Garantias Financeiras', 12, desc, img, emails, tags)
insert into Produto values (26, 'Garantias Judiciais', 12, desc, img, emails, tags)
insert into Produto values (27, 'Garantias Para Grandes Contratos Públicos/Privados', 12, desc, img, emails, tags)
insert into Produto values (28, 'Náutico', 13, desc, img, emails, tags)
insert into Produto values (29, 'Previdência Privada', 14, desc, img, emails, tags)
insert into Produto values (30, 'Residencial', 16, desc, img, emails, tags)
insert into Produto values (31, 'Responsabilidade Civil Geral', 17, desc, img, emails, tags)
insert into Produto values (32, 'Responsabilidade Civil Profissional', 17, desc, img, emails, tags)
insert into Produto values (33, 'Responsabilidade Civil Profissional Advogado', 15, desc, img, emails, tags)
insert into Produto values (34, 'Responsabilidade Civil Notário', 15, desc, img, emails, tags)
insert into Produto values (35, 'Responsabilidade Civil Profissional Contabilista', 15, desc, img, emails, tags)
insert into Produto values (36, 'Responsabilidade Civil Profissional Corretor De Imóveis', 15, desc, img, emails, tags)
insert into Produto values (37, 'Responsabilidade Civil Profissional Corretor De Seguros', 15, desc, img, emails, tags)
insert into Produto values (38, 'Responsabilidade Civil Profissional Dentistas', 15, desc, img, emails, tags)
insert into Produto values (39, 'Responsabilidade Civil Profissional Engenheiro E Arquiteto', 15, desc, img, emails, tags)
insert into Produto values (40, 'Responsabilidade Civil Profissional Eventos', 15, desc, img, emails, tags)
insert into Produto values (41, 'Responsabilidade Civil Profissional Médico', 15, desc, img, emails, tags)
insert into Produto values (42, 'Reta', 2, desc, img, emails, tags)
insert into Produto values (43, 'Risco Diversos', 19, desc, img, emails, tags)
insert into Produto values (44, 'Risco Engenharia', 18, desc, img, emails, tags)
insert into Produto values (45, 'Saúde', 20, desc, img, emails, tags)
insert into Produto values (46, 'Transporte', 21, desc, img, emails, tags)
insert into Produto values (47, 'Mototáxi', 1, desc, img, emails, tags)
insert into Produto values (48, 'D & O', 15, desc, img, emails, tags)
insert into Produto values (49, 'Consórcio', 8, desc, img, emails, tags)
insert into Produto values (50, 'Motofrete', 1, desc, img, emails, tags)
insert into Produto values (51, 'Acidentes Pessoais Passageiros', 1, desc, img, emails, tags)
insert into Produto values (52, 'Transporte - Cargas Perigosas', 21, desc, img, emails, tags)
insert into Produto values (53, 'Transporte - Internacional E Nacional', 21, desc, img, emails, tags)
insert into Produto values (54, 'Vida Individual', 22, desc, img, emails, tags)
insert into Produto values (55, 'Seguro Viagem', 22, desc, img, emails, tags)
insert into Produto values (56, 'Educacional', 22, desc, img, emails, tags)
insert into Produto values (57, 'Diet(diabéticos)', 22, desc, img, emails, tags)
insert into Produto values (58, 'Vida Acima 65 anos', 22, desc, img, emails, tags)
insert into Produto values (59, 'Freedom - Homoafetivo', 22, desc, img, emails, tags)
insert into Produto values (60, 'Vida Máxima Mulher', 22, desc, img, emails, tags)
insert into Produto values (61, 'Veiculos Especiais Acima De R$ 100.000,00', 5, desc, img, emails, tags)
insert into Produto values (62, 'Dental Empresarial Spg', 9, desc, img, emails, tags)
insert into Produto values (63, 'Empresarial - Grandes Riscos', 10, desc, img, emails, tags)
insert into Produto values (64, 'Bicicletas', 6, desc, img, emails, tags)
insert into Produto values (65, 'Vida Empresarial Spg', 22, desc, img, emails, tags)
insert into Produto values (66, 'Vida Empresarial Pme', 22, desc, img, emails, tags)
insert into Produto values (67, 'Vida Empresarial Capital Global', 22, desc, img, emails, tags)
insert into Produto values (68, 'Auto - Segurados E Veículos Restritos', 5, desc, img, emails, tags)
insert into Produto values (69, 'Responsabilidade Civil Eventos', 17, desc, img, emails, tags)
insert into Produto values (70, 'Responsabilidade Civil Geral', 17, desc, img, emails, tags)	
insert into Produto values (71, 'Garantias Ações Trabalhistas E Previdenciárias (cobertura adicional)', 12, desc, img, emails, tags)